-- =============================================================
-- 11_upload_contracts.sql
-- Upload contract tables for raw ingestion
-- Minimum common datasets:
-- inventory, purchase_order, receipt, shipment, return, sales, charge
-- =============================================================

-- ----- raw.upload_inventory_snapshot -----
CREATE TABLE IF NOT EXISTS raw.upload_inventory_snapshot (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT NOT NULL,
    source_file_name  TEXT NOT NULL,
    source_row_no     BIGINT NOT NULL,
    snapshot_date     DATE NOT NULL,
    warehouse_id      TEXT NOT NULL,
    item_id           TEXT NOT NULL,
    lot_id            TEXT,
    onhand_qty        DOUBLE PRECISION NOT NULL,
    sellable_qty      DOUBLE PRECISION,
    blocked_qty       DOUBLE PRECISION,
    expiry_date       DATE,
    mfg_date          DATE,
    qc_status         TEXT,
    hold_flag         BOOLEAN DEFAULT false,
    source_system     TEXT DEFAULT 'upload',
    uploaded_at       TIMESTAMP DEFAULT NOW(),
    UNIQUE (batch_id, source_file_name, source_row_no)
);

COMMENT ON TABLE raw.upload_inventory_snapshot IS '업로드 계약: 재고 스냅샷 원본';

-- ----- raw.upload_purchase_order -----
CREATE TABLE IF NOT EXISTS raw.upload_purchase_order (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT NOT NULL,
    source_file_name  TEXT NOT NULL,
    source_row_no     BIGINT NOT NULL,
    po_id             TEXT NOT NULL,
    po_date           DATE NOT NULL,
    supplier_id       TEXT NOT NULL,
    item_id           TEXT NOT NULL,
    qty_ordered       DOUBLE PRECISION NOT NULL,
    eta_date          DATE,
    unit_price        DOUBLE PRECISION,
    currency          TEXT,
    incoterms         TEXT,
    source_system     TEXT DEFAULT 'upload',
    uploaded_at       TIMESTAMP DEFAULT NOW(),
    UNIQUE (batch_id, source_file_name, source_row_no)
);

COMMENT ON TABLE raw.upload_purchase_order IS '업로드 계약: 발주 원본';

-- ----- raw.upload_receipt -----
CREATE TABLE IF NOT EXISTS raw.upload_receipt (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT NOT NULL,
    source_file_name  TEXT NOT NULL,
    source_row_no     BIGINT NOT NULL,
    receipt_id        TEXT NOT NULL,
    receipt_date      DATE NOT NULL,
    warehouse_id      TEXT NOT NULL,
    item_id           TEXT NOT NULL,
    qty_received      DOUBLE PRECISION NOT NULL,
    po_id             TEXT,
    lot_id            TEXT,
    expiry_date       DATE,
    mfg_date          DATE,
    qc_status         TEXT,
    source_system     TEXT DEFAULT 'upload',
    uploaded_at       TIMESTAMP DEFAULT NOW(),
    UNIQUE (batch_id, source_file_name, source_row_no)
);

COMMENT ON TABLE raw.upload_receipt IS '업로드 계약: 입고 원본';

-- ----- raw.upload_shipment -----
CREATE TABLE IF NOT EXISTS raw.upload_shipment (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT NOT NULL,
    source_file_name  TEXT NOT NULL,
    source_row_no     BIGINT NOT NULL,
    shipment_id       TEXT NOT NULL,
    ship_date         DATE NOT NULL,
    warehouse_id      TEXT NOT NULL,
    item_id           TEXT NOT NULL,
    qty_shipped       DOUBLE PRECISION NOT NULL,
    lot_id            TEXT,
    weight            DOUBLE PRECISION,
    volume_cbm        DOUBLE PRECISION,
    channel_order_id  TEXT,
    channel_store_id  TEXT,
    source_system     TEXT DEFAULT 'upload',
    uploaded_at       TIMESTAMP DEFAULT NOW(),
    UNIQUE (batch_id, source_file_name, source_row_no)
);

COMMENT ON TABLE raw.upload_shipment IS '업로드 계약: 출고 원본';

-- ----- raw.upload_return -----
CREATE TABLE IF NOT EXISTS raw.upload_return (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT NOT NULL,
    source_file_name  TEXT NOT NULL,
    source_row_no     BIGINT NOT NULL,
    return_id         TEXT NOT NULL,
    return_date       DATE NOT NULL,
    warehouse_id      TEXT NOT NULL,
    item_id           TEXT NOT NULL,
    qty_returned      DOUBLE PRECISION NOT NULL,
    lot_id            TEXT,
    channel_order_id  TEXT,
    reason            TEXT,
    disposition       TEXT,
    source_system     TEXT DEFAULT 'upload',
    uploaded_at       TIMESTAMP DEFAULT NOW(),
    UNIQUE (batch_id, source_file_name, source_row_no)
);

COMMENT ON TABLE raw.upload_return IS '업로드 계약: 반품 원본';

-- ----- raw.upload_sales -----
CREATE TABLE IF NOT EXISTS raw.upload_sales (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT NOT NULL,
    source_file_name  TEXT NOT NULL,
    source_row_no     BIGINT NOT NULL,
    settlement_id     TEXT NOT NULL,
    line_no           BIGINT NOT NULL,
    period            TEXT NOT NULL,
    channel_store_id  TEXT NOT NULL,
    item_id           TEXT,
    currency          TEXT NOT NULL,
    gross_sales       DOUBLE PRECISION NOT NULL,
    discounts         DOUBLE PRECISION,
    fees              DOUBLE PRECISION,
    refunds           DOUBLE PRECISION,
    net_payout        DOUBLE PRECISION,
    source_system     TEXT DEFAULT 'upload',
    uploaded_at       TIMESTAMP DEFAULT NOW(),
    UNIQUE (batch_id, source_file_name, source_row_no)
);

COMMENT ON TABLE raw.upload_sales IS '업로드 계약: 매출 / 정산 원본';

-- ----- raw.upload_charge -----
CREATE TABLE IF NOT EXISTS raw.upload_charge (
    raw_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT NOT NULL,
    source_file_name  TEXT NOT NULL,
    source_row_no     BIGINT NOT NULL,
    invoice_no        TEXT NOT NULL,
    invoice_line_no   BIGINT NOT NULL,
    charge_type       TEXT NOT NULL,
    amount            DOUBLE PRECISION NOT NULL,
    currency          TEXT NOT NULL,
    period            TEXT NOT NULL,
    invoice_date      DATE,
    vendor_partner_id TEXT,
    charge_basis      TEXT,
    reference_type    TEXT,
    reference_id      TEXT,
    channel_store_id  TEXT,
    warehouse_id      TEXT,
    country           TEXT,
    source_system     TEXT DEFAULT 'upload',
    uploaded_at       TIMESTAMP DEFAULT NOW(),
    UNIQUE (batch_id, source_file_name, source_row_no)
);

COMMENT ON TABLE raw.upload_charge IS '업로드 계약: 비용 원본';

-- RLS for upload contract tables
ALTER TABLE raw.upload_inventory_snapshot ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw.upload_purchase_order     ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw.upload_receipt            ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw.upload_shipment           ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw.upload_return             ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw.upload_sales              ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw.upload_charge             ENABLE ROW LEVEL SECURITY;

CREATE POLICY "upload_admin_full_access" ON raw.upload_inventory_snapshot
  FOR ALL USING ((auth.jwt() ->> 'role') = 'admin') WITH CHECK ((auth.jwt() ->> 'role') = 'admin');
CREATE POLICY "upload_admin_full_access" ON raw.upload_purchase_order
  FOR ALL USING ((auth.jwt() ->> 'role') = 'admin') WITH CHECK ((auth.jwt() ->> 'role') = 'admin');
CREATE POLICY "upload_admin_full_access" ON raw.upload_receipt
  FOR ALL USING ((auth.jwt() ->> 'role') = 'admin') WITH CHECK ((auth.jwt() ->> 'role') = 'admin');
CREATE POLICY "upload_admin_full_access" ON raw.upload_shipment
  FOR ALL USING ((auth.jwt() ->> 'role') = 'admin') WITH CHECK ((auth.jwt() ->> 'role') = 'admin');
CREATE POLICY "upload_admin_full_access" ON raw.upload_return
  FOR ALL USING ((auth.jwt() ->> 'role') = 'admin') WITH CHECK ((auth.jwt() ->> 'role') = 'admin');
CREATE POLICY "upload_admin_full_access" ON raw.upload_sales
  FOR ALL USING ((auth.jwt() ->> 'role') = 'admin') WITH CHECK ((auth.jwt() ->> 'role') = 'admin');
CREATE POLICY "upload_admin_full_access" ON raw.upload_charge
  FOR ALL USING ((auth.jwt() ->> 'role') = 'admin') WITH CHECK ((auth.jwt() ->> 'role') = 'admin');

CREATE POLICY "upload_ops_read" ON raw.upload_inventory_snapshot
  FOR SELECT USING ((auth.jwt() ->> 'role') = 'ops');
CREATE POLICY "upload_ops_read" ON raw.upload_purchase_order
  FOR SELECT USING ((auth.jwt() ->> 'role') = 'ops');
CREATE POLICY "upload_ops_read" ON raw.upload_receipt
  FOR SELECT USING ((auth.jwt() ->> 'role') = 'ops');
CREATE POLICY "upload_ops_read" ON raw.upload_shipment
  FOR SELECT USING ((auth.jwt() ->> 'role') = 'ops');
CREATE POLICY "upload_ops_read" ON raw.upload_return
  FOR SELECT USING ((auth.jwt() ->> 'role') = 'ops');
CREATE POLICY "upload_ops_read" ON raw.upload_sales
  FOR SELECT USING ((auth.jwt() ->> 'role') = 'ops');
CREATE POLICY "upload_ops_read" ON raw.upload_charge
  FOR SELECT USING ((auth.jwt() ->> 'role') = 'ops');
